#create namespace metrics-load-test
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-load-test
spec:
  finalizers:
  - kubernetes
---
#create deployment avalanche
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: metrics-load-test
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: pg-avalanche
        image: quay.io/aabhishe/avalanche:latest
        args:
        - "--metric-count=50000"
        - "--label-count=10"
        - "--series-count=5"
        - "--port=9001"
        ports:
        - containerPort: 9001
---
#create service avalanche-svc
apiVersion: v1
kind: Service
metadata:
  annotations:
    metrics.dynatrace.com/path: /metrics
    metrics.dynatrace.com/port: "9001"
    metrics.dynatrace.com/scrape: "true"
  name: avalanche-svc
  namespace: metrics-load-test
  labels:
    app: avalanche
spec:
  ports:
  # the port that this service should serve on
  - port: 9001
    targetPort: 9001
    name: http-avalanche
  type: ClusterIP
  clusterIP: None
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: avalanche